name: etcd-3
initial-advertise-peer-urls: http://127.0.0.2:2392 
listen-peer-urls: http://127.0.0.2:2392
listen-client-urls: http://127.0.0.2:2389,http://localhost:2389 
advertise-client-urls: http://127.0.0.2:2389 
initial-cluster-token: etcd-cluster
initial-cluster: etcd-1=http://127.0.0.2:2390,etcd-2=http://127.0.0.2:2391,etcd-3=http://127.0.0.2:2392
initial-cluster-state: new